version: '3.8'

services:
  # MinIO Object Storage
  minio:
    image: minio/minio
    container_name: footfit-minio
    restart: always
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: your_minio_access_key
      MINIO_ROOT_PASSWORD: your_minio_secret_key
    ports:
      - "9000:9000"
      - "9001:9001"
    deploy:
      resources:
        limits:
          memory: 2G
    command: server /data --console-address ":9001"

  # MinIO Client (MC) for bucket setup
  minio-client:
    image: minio/mc
    container_name: footfit-minio-client
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add myminio http://minio:9000 your_minio_access_key your_minio_secret_key;
      /usr/bin/mc mb --ignore-existing myminio/videos;
      /usr/bin/mc mb --ignore-existing myminio/profiles;
      /usr/bin/mc mb --ignore-existing myminio/teams;
      /usr/bin/mc mb --ignore-existing myminio/products;
      /usr/bin/mc mb --ignore-existing myminio/temp;
      /usr/bin/mc policy set download myminio/videos;
      /usr/bin/mc policy set download myminio/profiles;
      /usr/bin/mc policy set download myminio/teams;
      /usr/bin/mc policy set download myminio/products;
      exit 0;
      "

  # Video Processing Service (FFmpeg)
  video-processor:
    build:
      context: ./video-processor
      dockerfile: Dockerfile
    container_name: footfit-video-processor
    restart: always
    depends_on:
      - minio
    environment:
      NODE_ENV: production
      PORT: 3001
      HOST: 0.0.0.0
      MINIO_ENDPOINT: footfit-minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: your_minio_access_key
      MINIO_SECRET_KEY: your_minio_secret_key
      MINIO_USE_SSL: "false"
      MINIO_BUCKET_NAME: videos
      SUPABASE_URL: https://your-project-ref.supabase.co
      SUPABASE_SERVICE_KEY: your-supabase-service-key
      FFMPEG_PATH: /usr/bin/ffmpeg
      FFPROBE_PATH: /usr/bin/ffprobe
      TEMP_DIR: /app/temp
      NODE_OPTIONS: "--max-old-space-size=2048"
      MAX_VIDEO_SIZE_MB: "50"
      VIDEO_PROCESSING_TIMEOUT_SEC: "300"
      THUMBNAIL_QUALITY: "80"
      THUMBNAIL_SIZE: "320x180"
      MAX_VIDEO_DURATION_SEC: "60"
      VIDEO_OUTPUT_FORMAT: "mp4"
      VIDEO_BITRATE: "1500k"
      VIDEO_RESOLUTION: "720p"
      SERVER_PORT: "3001"
      LOG_LEVEL: "info"
    volumes:
      - ./video-processor:/app
      - ./temp-videos:/app/temp
    ports:
      - "3001:3001"
    deploy:
      resources:
        limits:
          memory: 3G

  # Nginx Proxy
  nginx:
    image: nginx:alpine
    container_name: footfit-nginx
    restart: always
    depends_on:
      - minio
      - video-processor
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/data:/var/www/html
      - ./nginx/logs:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    deploy:
      resources:
        limits:
          memory: 1G

volumes:
  minio_data:

networks:
  default:
    driver: bridge 